version: "3"
services:
    mongodb:
      container_name: mongodb
      image: mongo:5.0
      restart: always
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: admin12
      volumes:
        - "myapp2:/data/db/"
    redis:
      container_name: redis
      image: redis:6.2.6
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - "myapp2:/data/db/"
    redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
        - REDIS_HOSTS=local:redis:6379
      ports:
        - "8081:8081"

volumes:
  myapp2:
    driver: local