version: "3"
services:
    mongodb:
      container_name: mongodb
      image: mongo:5.0
      restart: always
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: admin12
      volumes:
        - "myapp2:/data/db/"
    redis:
      container_name: redis
      image: redis:6.2.6
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - "myapp2:/data/db/"
volumes:
  myapp2:
    driver: local