export const teacherListLimit=10
export const departmentMajorsLimit = 10
export const adminstrationListLimit=10
export const contestListLimit=10
export const departmentListLimit=10
export const departmentSubjectListLimit=10
export const subjectListLimit=10
export const talentedStudentListLimit=10
export const resourceCategoryListLimit = 10
export const resourcesListLimit=10
export const newsPaginationLimit = 10
export const majorsListLimit=10
export const defaultLang = "uz"
export const departmentSubjectDegrees = ["bachelor","master","doctoral"]
export const supportedLangs = ["uz","ru","en"]