export interface AdminstrationDataProps{
    body:{
        teacherId:string;
        departmentId:string;
        reception_time_starts:string;
        reception_time_ends:string
    },
    withoutTeacherId:{
        departmentId:string;
        reception_time_starts:string;
        reception_time_ends:string
    },
    withoutDepartmentId:{
        teacherId:string;
        reception_time_starts:string;
        reception_time_ends:string
    },
    withoutReceptionTimeStart:{
        teacherId:string;
        departmentId:string;
        reception_time_ends:string
    },
    withoutReceptionTimeEnd:{
        teacherId:string;
        departmentId:string;
        reception_time_starts:string;
    },
    withWrongTypeTeacherId:{
        teacherId:number;
        departmentId:string;
        reception_time_starts:string;
        reception_time_ends:string
    },
    withWrongTypeDepartmentId:{
        teacherId:string;
        departmentId:number;
        reception_time_starts:string;
        reception_time_ends:string
    },
    withWrongTypeReceptionTimeStart:{
        teacherId:string;
        departmentId:string;
        reception_time_starts:number;
        reception_time_ends:string
    },
    withWrongTypeReceptionTimeEnd:{
        teacherId:string;
        departmentId:string;
        reception_time_starts:string;
        reception_time_ends:number
    }
}